<h2>Horario</h2>
<p>Te mostramos el horario de nuestro especiliasta</p>
<div class="table-responsive">          
<table class="table">
	<thead>
	      <tr>
	        <th>Hora/Día</th>
	        <th>Lunes</th>
	        <th>Martes</th>
	        <th>Miercoles</th>
	        <th>Jueves</th>
	        <th>Viernes</th>
	        <th>Sabado</th>
	        <th>Domingo</th>
	      </tr>
	</thead>
	<tbody>
	    <tr>
	    	<td>08:00</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>Huancayo</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>-</td>
	    </tr>
	    <tr>
	    	<td>09:00</td>
	    	<td>-</td>
	    	<td>Concepción</td>
	    	<td>Huancayo</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>-</td>
	    </tr>
	    <tr>
	    	<td>10:00</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>Huancayo</td>
	    	<td>-</td>
	    	<td>-</td>
	    </tr>
	    <tr>
	    	<td>11:00</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>-</td>
	    	<td>Huancayo</td>
	    	<td>-</td>
	    	<td>-</td>
	    </tr>
	</tbody>
</table>
</div>